import './globals.css'
import { Inter } from 'next/font/google'
import cn from 'classnames';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "flex flex-col items-center justify-center w-screen min-h-screen min-w-screen p-5 bg-gray-50 text-gray-800 dark:bg-gray-900 overflow-hidden",
        )}
        >
        {children}
      </body>
    </html>
  )
}
